### ISSUE TITLE
Engine Mk2TwinTurboJetAB "wet" mode as "minthrust = 200"

### ISSUE THREAD

**Issue by Galenmacil** [linuxgurugamer/QuizTechAeroPackContinued#17]
Only atmospheric engine that has this set to something other than zero. This makes it impossible to slow down when afterburners are engage even at zero throttle.

**Comment by linuxgurugamer** [comment]
Thanks, fixing now

**Comment by linuxgurugamer** [comment]
Actually, that's intentional.  If the Afterburners are engaged, you are dumping extra fuel into the engine, so it makes sense to not be able to reduce speed to 0.  Just disengage AB mode when you want to go to 0 throttle
