### ISSUE TITLE
Bad MM patch related to FAR mod.

### ISSUE THREAD

**Issue by Galenmacil** [linuxgurugamer/QuizTechAeroPackContinued#2]
After struggling for a while with a few mod applying patches to parts even though FAR is not installed, I sent an issue to Sarbian, maintainer of MM. Take a look at what he said:

https://github.com/sarbian/ModuleManager/issues/59#event-830838883

It seems using FOR[] as directive declare whatever is in the bracket as installed! A few mods have trouble with this, MK2 and MK3 expansion to name just two.

I hope this help in improving the mod.

**Comment by linuxgurugamer** [comment]
Thanks.  I saw that you submitted  a number of PRs, I assume they are related to this?

If so, can you close this ?
thanks
