### ISSUE TITLE
MK2 "Nerva" Engine generate error in log and decouple function can't be staged...

### ISSUE THREAD

**Issue by Galenmacil** [linuxgurugamer/QuizTechAeroPackContinued#9]
It can only be decoupled manually by left clicking the part itself and selecting decouple. Fairings are working correctly though.

I don't know how to fix the decoupler problem. Here an excerpt from the .LOG file:

[LOG 13:41:37.350] PartLoader: Compiling Part 'QuizTechAeroContinued/Parts/Engine/Mk2_NERVA/Mk_NERVA/Mk2_NERVA'
[ERR 13:41:37.356] Cannot find fx group of that name for decoupler

[ERR 13:41:37.361] Cannot find fx group of that name for decoupler

[LOG 13:41:37.364] PartLoader: Part 'QuizTechAeroContinued/Parts/Engine/Mk2_NERVA/Mk_NERVA/Mk2_NERVA' has no database record. Creating.
[ERR 13:41:37.367] Cannot find fx group of that name for decoupler

**Comment by linuxgurugamer** [comment]
is this still an issue?

**Comment by Galenmacil** [comment]
More than two years later... I can tell you that yes, the problem is still present in KSP 1.7.2. I use a custom MM patch to remove the faulty decoupler module on the Nerva.

**Comment by linuxgurugamer** [comment]
Fixed in upcoming release
